/**
 * AI Model Service
 * Unified orchestration layer across local Gemma 3 (Ollama), Google Gemini 2.5 / Gemma,
 * and ultra-fast Groq fallback, backed by the resilient Pedagogical Heuristic Engine.
 *
 * FLOW:
 *   Student prompt + Chat History + Teaching DNA (from DB)
 *     → System Prompt (topic-agnostic, dynamic)
 *     → Gemma 3 (Ollama) → JSON parse/normalise
 *     → Gemini 2.5 (if Ollama down)
 *     → Groq (if Gemini unavailable)
 *     → Generic fallback (if ALL tiers fail)
 *
 * The DB provides CONTEXT (student profile, strategy DNA, past scores) — NOT pre-canned answers.
 * All actual educational content is generated by the LLM on every call.
 */

const { GEMMA3_COGNITIVE_PROMPT, DIAGNOSIS_SYSTEM_PROMPT, ADAPTIVE_RESPONSE_PROMPT } = require('../constants/systemPrompts');
const { parseDiagnosisResponse } = require('./diagnosisService');
const { callGroqTutor } = require('./groqFallbackService');
const ollamaService = require('./ollamaService');

/**
 * Calls Gemini Generative API via REST with clean timeout handling
 */
const callGeminiApi = async (systemInstruction, userContent, model = 'gemini-2.5-flash') => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY not configured.');
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 10000);

  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: controller.signal,
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: systemInstruction }]
        },
        contents: [
          {
            role: 'user',
            parts: [{ text: userContent }]
          }
        ],
        generationConfig: {
          temperature: 0.3,
          responseMimeType: 'application/json'
        }
      })
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errBody = await response.text();
      throw new Error(`Gemini API HTTP ${response.status}: ${errBody}`);
    }

    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text;
  } catch (err) {
    clearTimeout(timeoutId);
    throw err;
  }
};

/**
 * Format chat history for use inside the system prompt (text block) and
 * for the Ollama messages array (conversation turns).
 *
 * @param {Array} chatHistory - Messages from TutorContext: [{role, content|text}]
 * @param {number} limit - How many recent turns to include
 * @returns {{ systemHistoryBlock: Array, ollamaMessages: Array }}
 */
const formatChatHistory = (chatHistory = [], limit = 6) => {
  const filtered = (chatHistory || [])
    .filter(m => m && (m.text || m.content))
    .slice(-limit)
    .map(m => ({
      role: m.role === 'user' ? 'user' : 'assistant',
      content: typeof m.content === 'string'
        ? m.content
        : (m.text || m.remediationContent || '')
    }))
    .filter(m => m.content.trim());

  return filtered;
};

/**
 * Primary Cognitive Pedagogy Turn:
 *
 * 1. Reads student's actual message + recent chat history (for context)
 * 2. Reads Teaching DNA from DB (passed as dnaProfile) to personalise strategy
 * 3. Builds a topic-agnostic system prompt that includes chat history
 * 4. Calls Gemma 3 → Gemini → Groq → generic fallback in sequence
 * 5. Returns normalised JSON with all educational content from the LLM
 *
 * KEY: The LLM generates ALL content. DB data is context, not answers.
 *
 * @param {object} params
 * @param {string}  params.studentSubmission - What the student typed
 * @param {string}  params.topicContext      - Session topic label (e.g., "Recursion Foundations")
 * @param {object}  params.dnaProfile        - Teaching DNA weights from DB
 * @param {string}  params.activeStrategy    - Current dominant strategy
 * @param {Array}   params.chatHistory       - Recent chat turns for context
 * @returns {Promise<object>} Normalised LLM response
 */
const { buildCognitiveDirective } = require('./cognitivePromptBuilder');

/**
 * Primary Cognitive Pedagogy Turn:
 *
 * 1. Cognitive Prompt Builder analyzes the student input (detects acronyms like CSE, DBMS, OS, intent, Teaching DNA).
 * 2. Structures an optimized directive for Gemma 3.
 * 3. Calls Gemma 3 via Ollama (or fallback tier).
 * 4. Returns 100% dynamic, generated content from the AI model (zero canned strings).
 */
const processCognitiveTurn = async ({
  studentSubmission,
  topicContext = 'Computer Science',
  dnaProfile = {},
  activeStrategy = 'analogy',
  chatHistory = [],
  turnContext = null
}) => {
  // ── Cognitive Prompt Building & Intent Analysis ───────────────────────────
  const directive = buildCognitiveDirective(studentSubmission, activeStrategy, topicContext);
  const isGreeting = directive.isGreeting;
  const isContinuation = turnContext?.isContinuation || false;

  // Topic context and system instruction
  const effectiveTopic = isGreeting ? 'General Learning' : (directive.detectedConcept || topicContext);
  const systemInstruction = GEMMA3_COGNITIVE_PROMPT(dnaProfile, effectiveTopic);

  // Format recent conversation turns (only for continuations)
  const historyTurns = (isGreeting || turnContext?.isNewTopic) ? [] : chatHistory;
  const formattedHistory = formatChatHistory(historyTurns, 6);

  // User prompt structured by the Cognitive Prompt Builder
  const userPrompt = directive.gemmaDirective;

  // Ollama messages: system + history + current user message
  const ollamaMessages = [
    ...formattedHistory,
    { role: 'user', content: userPrompt }
  ];

  // For Gemini/Groq: combine history into user message for single-turn APIs
  const historyPrefix = formattedHistory.length > 0
    ? `Recent conversation:\n${formattedHistory.map(m => `${m.role === 'user' ? 'Student' : 'Tutor'}: ${m.content}`).join('\n')}\n\n`
    : '';
  const singleTurnUserPrompt = `${historyPrefix}${userPrompt}`;

  // ── Tier 1: Local Gemma 3 via Ollama ────────────────────────────────────
  try {
    const isOllamaUp = await ollamaService.isAvailable();
    if (isOllamaUp) {
      console.log('🤖 [Gemma 3 Local] Invoking Gemma 3 via Ollama...');
      const rawGemma = await ollamaService.generateChatResponse(
        ollamaMessages,
        systemInstruction
      );
      if (rawGemma && rawGemma.trim() && rawGemma !== '{}') {
        const parsed = parseDiagnosisResponse(rawGemma, studentSubmission);
        // Accept if we got real educational content (at least 30 chars)
        if (parsed.remediationContent && parsed.remediationContent.length > 30) {
          return { ...parsed, modelSource: 'gemma-3 (local)' };
        }
      }
      console.warn('⚠️  Gemma 3 returned empty or minimal response, trying next tier...');
    }
  } catch (gemmaErr) {
    console.warn(`⚠️  Gemma 3 Ollama query failed: ${gemmaErr.message}`);
  }

  // ── Tier 2: Google Gemini 2.5 ────────────────────────────────────────────
  try {
    console.log('🌐 [Gemini 2.5] Falling back to Google Gemini Generative API...');
    const rawResult = await callGeminiApi(systemInstruction, singleTurnUserPrompt);
    if (rawResult && rawResult.trim()) {
      const parsed = parseDiagnosisResponse(rawResult, studentSubmission);
      return { ...parsed, modelSource: 'gemini-2.5' };
    }
  } catch (geminiError) {
    console.warn(`⚠️  Gemini API failed: ${geminiError.message}`);
  }

  // ── Tier 3: Groq Cloud LLM ───────────────────────────────────────────────
  try {
    console.log('⚡ [Groq Fallback] Attempting fast Groq cloud inference...');
    const groqResult = await callGroqTutor(singleTurnUserPrompt, systemInstruction, activeStrategy);
    if (groqResult) {
      const parsed = parseDiagnosisResponse(JSON.stringify(groqResult), studentSubmission);
      return { ...parsed, modelSource: 'groq-fallback' };
    }
  } catch (groqErr) {
    console.warn(`⚠️  Groq fallback failed: ${groqErr.message}`);
  }

  // ── Tier 4: Generic fallback (honest, no fake content) ───────────────────
  console.log('🛡️  [Generic Fallback] All AI tiers unavailable — returning honest fallback.');
  const { buildGenericFallback } = require('./diagnosisService');
  return { ...buildGenericFallback(studentSubmission), modelSource: 'offline-fallback' };
};

/**
 * Backwards compatibility shims
 */
const diagnoseStudentResponse = async (studentSubmission, topicContext = 'Computer Science') => {
  return await processCognitiveTurn({ studentSubmission, topicContext });
};

const generateAdaptiveTutorResponse = async ({
  dnaProfile,
  activeStrategy,
  studentPrompt,
  diagnosis,
  topicContext = 'Computer Science',
  chatHistory = []
}) => {
  const result = await processCognitiveTurn({
    studentSubmission: studentPrompt,
    topicContext,
    dnaProfile,
    activeStrategy,
    chatHistory
  });

  return {
    strategyUsed: activeStrategy || result.recommendedStrategy || 'analogy',
    headline: result.headline,
    coreExplanation: result.remediationContent,
    visualDiagram: result.visualDiagram,
    codeSnippet: result.codeSnippet,
    socraticCheck: result.quickCheckQuestion?.question,
    practicePrompt: result.quickCheckQuestion ? {
      question: result.quickCheckQuestion.question,
      options: result.quickCheckQuestion.options,
      correctIndex: result.quickCheckQuestion.correctOptionIndex,
      hint: result.quickCheckQuestion.hint
    } : null,
    modelSource: result.modelSource
  };
};

module.exports = {
  callGeminiApi,
  processCognitiveTurn,
  diagnoseStudentResponse,
  generateAdaptiveTutorResponse
};
